"""make payment id auto increment

Revision ID: a78568257956
Revises: 9bf7cf6a5970
Create Date: 2024-02-22 11:10:50.261286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a78568257956'
down_revision: Union[str, None] = '9bf7cf6a5970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('id', sa.Integer(), autoincrement=True, primary_key=True, nullable=False))
    op.drop_column('payments', 'payment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('payments', 'id')
    # ### end Alembic commands ###
