"""make payment id col

Revision ID: c53c649a7287
Revises: a78568257956
Create Date: 2024-02-22 12:27:29.847198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c53c649a7287'
down_revision: Union[str, None] = 'a78568257956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_id', sa.Integer(), nullable=False, autoincrement=True, primary_key=True))
    op.drop_column('payments', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('payments', 'payment_id')
    # ### end Alembic commands ###
